Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(example.py:526121): Gdk-CRITICAL **: 10:51:15.392: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

Loading data...

Training...

Evaluating...
accuracy  0.6833333333333333
classification report...
              precision    recall  f1-score   support

         1.0       0.80      0.86      0.83        14
         2.0       0.93      0.93      0.93        14
         3.0       0.61      0.58      0.59        19
         4.0       0.38      0.38      0.38        13

    accuracy                           0.68        60
   macro avg       0.68      0.69      0.68        60
weighted avg       0.68      0.68      0.68        60

